#Sample Personal Access Token

name: Pull request labeler
on:
  workflow_dispatch
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
